version: '3.0'

services:
    php:
        container_name: tree_php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                UID:      ${UID}
                GID:      ${GID}
        volumes:
            - ../:${PROJECT_DIR}
        working_dir: ${PROJECT_DIR}
        extra_hosts:
            - 'dockerhost:112.213.91.169'
