version: '3.0'

services:
    apache:
        build:
            context: ./docker/apache
            args:
                UID: ${UID}
        ports:
            - '80:80'
            - '1510:1510'
        volumes:
            - ../:${PROJECT_DIR}
            - ./docker/logs/apache:/usr/local/apache2/logs/
        working_dir: ${PROJECT_DIR}

    mysql:
        build: ./docker/mysql
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER:          user
            MYSQL_PASSWORD:      userpass
            MYSQL_ROOT_PASSWORD: root

    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: ${TIMEZONE}
                UID:      ${UID}
        volumes:
            - ../:${PROJECT_DIR}
        working_dir: ${PROJECT_DIR}

volumes:
    db_data:
