version: '3.0'

services:
    apache:
        container_name: apache
        build:
            context: ./apache
            args:
                UID: ${UID}
                GID: ${GID}
        ports:
            - '80:80'
            - '1510:1510'
        volumes:
            - /var/www/html:/var/www/html
            - ./logs/apache:/usr/local/apache2/logs/

    mysql:
        container_name: mysql
        build: ./mysql
        volumes:
            - /var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER:          user
            MYSQL_PASSWORD:      userpass
            MYSQL_ROOT_PASSWORD: root

    php:
        container_name: php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                UID:      ${UID}
                GID:      ${GID}
        volumes:
            - /var/www/html:/var/www/html
        working_dir: /var/www/html
